### ISSUE TITLE
What can be done to help?

### ISSUE THREAD

**Issue by giraffeinaspeedo** [emil0r/reverie#1]
Is there any sort of list of what needs to be done and what is being worked on, etc.? Anywhere to look if someone is interested in contributing? Documentation? Wiki? Examples?

Seems like a really neat project. :)

**Comment by emil0r** [comment]
I'm gearing up for a first public official release. There will be some pieces missing in that release, but I feel it's better to have something, rather than nothing as well as get some feedback.

As for things that needs to be done: there is no shortage there, but I would want an official release out the door first so that people can orient themselves first and have a first hand look at what's available. UI is one rather big area that could do a lot of work as I've had to focus on the system itself for now. ez-database, which I broke out of reverie, needs to support transactions among other things and is also something I have not had time to properly do.

Documentation and examples will live on reveriecms.org once I've written that up. The current plan is to take a great deal of inspiration from django on how to organize the site. If anyone has extensive experience with writing documentation for a project like this I'd like to hear from them.

**Comment by giraffeinaspeedo** [comment]
Thanks for the response!

Part of the reason I asked was because I'd love to help. I've been reading through the code base already but it's (obviously) quite a big project. I was contracted to write documentation for Iron.io, and have written a good amount for another open source project or two. I'd love to help out.

I was planning on just going it alone anyway, but I was hoping you might've had some direction or notes or anything you could put up. The main concern I had was if there was going to be any main huge rewrites or refactoring projects you had planned. I believe I saw somewhere you saying there was a bit of a rewrite planned, and I didn't really want to study the code if it would all be different in a week's time.

If there's no other direction or anything that you have to share, I'm more than happy to just go it alone for a bit and hopefully get some notes of my own up.

Thank you

**Comment by emil0r** [comment]
Maybe this will help a bit then:  https://github.com/emil0r/reverie-template/issues/1#issuecomment-141755794

**Comment by emil0r** [comment]
Are you on clojurians slack?

**Comment by giraffeinaspeedo** [comment]
No, I am not. I go on the #clojure irc channel on freenode, or you can email me.
